### ISSUE TITLE
apt-get upgrade failing on Wheezy

### ISSUE THREAD

**Issue by alfiedotwtf** [corbinlc/gnuroot#10]
On a newly created chroot:
- apt-get update
- apt-get upgrade

It goes through the upgrade as normal and then fails when trying to upgrade tzdata:

  Preparing to replace tzdata 2013h-0wheezy1 (using .../tzdata_2014a-Owheezy1_all.deb)...
  Setting up tzdata (2014a-0wheezy1) ...
  /var/lib/dpkg/info/tzdata.postinst: 32: /var/lib/dpkg/info/tzdata.postinst: restorecon: Operation not permitted
dpkg: error processing tzdata (--configure):
    subprocess installed post-installation script returned error exit status 2

**Comment by lapsio** [comment]
I'm having the same error

**Comment by lapsio** [comment]
I've just removed this package however it was marked as essential xD. Oh well, hope It won't break too many apps.

**Comment by alfiedotwtf** [comment]
I've only just started playing with Debian on Android. GNURoot was the first one I looked at and it looked promising, but I've now switched to "Lil' Debi" as it works out of the box (minus some warnings). I'm still keen on evaluating this as I like having options.

**Comment by pianoman466** [comment]
See this link: http://www.linuxquestions.org/questions/debian-26/debian-wheezy-amd64-fail-to-configure-tzdata-everything-got-stuck-4175412151/

I just replaced the "set -e" with "set -x" in /var/lib/dpkg/info/tzdata.postinst and everything seemed to work ok.

**Comment by corbinlc** [comment]
I have pushed a new version of GNURoot to the Play Store just now (give it a couple of hours to show up).  It fixes this issue.  The problem was the default PATH inside the GNURoot rootfs was allowing executables to be found which were outside the rootfs and will not run properly from GNURoot currently.  Specifically it was finding and trying to run /system/bin/restorecon.  This is not needed, but because it was found in the search path, it caused trouble.

**Comment by alfiedotwtf** [comment]
Excellent, thanks for the fix :)
